[functions]
  directory = "routers"

[[redirects]]
  from = "/*"
  to = "/"
  status = 200

[[redirects]]
  from = "/api/v2/*"
  to = "/"
  status = 200




[build]
  command = "npm install"
  publish = "/"
