[functions]
  directory = "build"

[[redirects]]
  from = "/api/v2/user/*"
  to = "/"
  status = 200

[[redirects]]
  from = "/api/v2/admin/*"
  to = "/"
  status = 200

[[redirects]]
  from = "/api/v2/product/*"
  to = "/"
  status = 200

[[redirects]]
  from = "/api/v2/category/*"
  to = "/"
  status = 200


[build]
  command = "npm install"
  publish = "/"
