[functions]
  external_node_modules = ["express"]
  node_bundler = "esbuild"

[[redirects]]
  force = true
  from = "/*"
  to = "/"
  status = 200

[[redirects]]
  force = true
  from = "/api/v2/*"
  status = 200
  to = "/"

[build]
command = "npm run build"
publish = "/"

