[[redirects]]
from = "/*"
to = "/"
status = 200


[build]
  command = "npm install"
  publish = "/"

[context.production.environment]
  NODE_VERSION = "14"

[context.develop.environment]
  NODE_VERSION = "14"