services:
  - type: web
    name: my-web-service
    env: node
    plan: free
    buildCommand: "npm install && npm run build"
    startCommand: "npm start"
    envVars:
      - key: NODE_VERSION
        value: "14"
    staticPublishPath: build
